version: '3.5'
services:

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer
    ports:
      - "6432:5432"
    environment:
       - DB_USER=myuser
       - DB_PASSWORD=postgres
       - DB_HOST=db
       - POOL_MODE=transaction
       - MAX_CLIENT_CONN=200
    depends_on:
      - db

volumes:
  pg_data: